// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: v1/cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Cmd:
	//
	//	*Command_StoreValue
	//	*Command_LoadValue
	//	*Command_AppendEntries
	//	*Command_RequestVote
	//	*Command_InstallSnapshot
	//	*Command_TimeoutNow
	Cmd isCommand_Cmd `protobuf_oneof:"cmd"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetCmd() isCommand_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *Command) GetStoreValue() *StoreValue {
	if x, ok := x.GetCmd().(*Command_StoreValue); ok {
		return x.StoreValue
	}
	return nil
}

func (x *Command) GetLoadValue() *LoadValue {
	if x, ok := x.GetCmd().(*Command_LoadValue); ok {
		return x.LoadValue
	}
	return nil
}

func (x *Command) GetAppendEntries() *AppendEntriesRequest {
	if x, ok := x.GetCmd().(*Command_AppendEntries); ok {
		return x.AppendEntries
	}
	return nil
}

func (x *Command) GetRequestVote() *RequestVoteRequest {
	if x, ok := x.GetCmd().(*Command_RequestVote); ok {
		return x.RequestVote
	}
	return nil
}

func (x *Command) GetInstallSnapshot() *InstallSnapshotRequest {
	if x, ok := x.GetCmd().(*Command_InstallSnapshot); ok {
		return x.InstallSnapshot
	}
	return nil
}

func (x *Command) GetTimeoutNow() *TimeoutNowRequest {
	if x, ok := x.GetCmd().(*Command_TimeoutNow); ok {
		return x.TimeoutNow
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_StoreValue struct {
	StoreValue *StoreValue `protobuf:"bytes,1,opt,name=store_value,json=storeValue,proto3,oneof"`
}

type Command_LoadValue struct {
	LoadValue *LoadValue `protobuf:"bytes,2,opt,name=load_value,json=loadValue,proto3,oneof"`
}

type Command_AppendEntries struct {
	AppendEntries *AppendEntriesRequest `protobuf:"bytes,3,opt,name=append_entries,json=appendEntries,proto3,oneof"`
}

type Command_RequestVote struct {
	RequestVote *RequestVoteRequest `protobuf:"bytes,4,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type Command_InstallSnapshot struct {
	InstallSnapshot *InstallSnapshotRequest `protobuf:"bytes,5,opt,name=install_snapshot,json=installSnapshot,proto3,oneof"`
}

type Command_TimeoutNow struct {
	TimeoutNow *TimeoutNowRequest `protobuf:"bytes,6,opt,name=timeout_now,json=timeoutNow,proto3,oneof"`
}

func (*Command_StoreValue) isCommand_Cmd() {}

func (*Command_LoadValue) isCommand_Cmd() {}

func (*Command_AppendEntries) isCommand_Cmd() {}

func (*Command_RequestVote) isCommand_Cmd() {}

func (*Command_InstallSnapshot) isCommand_Cmd() {}

func (*Command_TimeoutNow) isCommand_Cmd() {}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//
	//	*CommandResponse_StoreValue
	//	*CommandResponse_LoadValue
	//	*CommandResponse_AppendEntries
	//	*CommandResponse_RequestVote
	//	*CommandResponse_InstallSnapshot
	//	*CommandResponse_TimeoutNow
	Resp isCommandResponse_Resp `protobuf_oneof:"resp"`
	// error message in case of error
	Error string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{1}
}

func (m *CommandResponse) GetResp() isCommandResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *CommandResponse) GetStoreValue() *StoreValueResponse {
	if x, ok := x.GetResp().(*CommandResponse_StoreValue); ok {
		return x.StoreValue
	}
	return nil
}

func (x *CommandResponse) GetLoadValue() *LoadValueResponse {
	if x, ok := x.GetResp().(*CommandResponse_LoadValue); ok {
		return x.LoadValue
	}
	return nil
}

func (x *CommandResponse) GetAppendEntries() *AppendEntriesResponse {
	if x, ok := x.GetResp().(*CommandResponse_AppendEntries); ok {
		return x.AppendEntries
	}
	return nil
}

func (x *CommandResponse) GetRequestVote() *RequestVoteResponse {
	if x, ok := x.GetResp().(*CommandResponse_RequestVote); ok {
		return x.RequestVote
	}
	return nil
}

func (x *CommandResponse) GetInstallSnapshot() *InstallSnapshotResponse {
	if x, ok := x.GetResp().(*CommandResponse_InstallSnapshot); ok {
		return x.InstallSnapshot
	}
	return nil
}

func (x *CommandResponse) GetTimeoutNow() *TimeoutNowResponse {
	if x, ok := x.GetResp().(*CommandResponse_TimeoutNow); ok {
		return x.TimeoutNow
	}
	return nil
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isCommandResponse_Resp interface {
	isCommandResponse_Resp()
}

type CommandResponse_StoreValue struct {
	StoreValue *StoreValueResponse `protobuf:"bytes,1,opt,name=store_value,json=storeValue,proto3,oneof"`
}

type CommandResponse_LoadValue struct {
	LoadValue *LoadValueResponse `protobuf:"bytes,2,opt,name=load_value,json=loadValue,proto3,oneof"`
}

type CommandResponse_AppendEntries struct {
	AppendEntries *AppendEntriesResponse `protobuf:"bytes,3,opt,name=append_entries,json=appendEntries,proto3,oneof"`
}

type CommandResponse_RequestVote struct {
	RequestVote *RequestVoteResponse `protobuf:"bytes,4,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type CommandResponse_InstallSnapshot struct {
	InstallSnapshot *InstallSnapshotResponse `protobuf:"bytes,5,opt,name=install_snapshot,json=installSnapshot,proto3,oneof"`
}

type CommandResponse_TimeoutNow struct {
	TimeoutNow *TimeoutNowResponse `protobuf:"bytes,6,opt,name=timeout_now,json=timeoutNow,proto3,oneof"`
}

func (*CommandResponse_StoreValue) isCommandResponse_Resp() {}

func (*CommandResponse_LoadValue) isCommandResponse_Resp() {}

func (*CommandResponse_AppendEntries) isCommandResponse_Resp() {}

func (*CommandResponse_RequestVote) isCommandResponse_Resp() {}

func (*CommandResponse_InstallSnapshot) isCommandResponse_Resp() {}

func (*CommandResponse_TimeoutNow) isCommandResponse_Resp() {}

type StoreValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StoreValue) Reset() {
	*x = StoreValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreValue) ProtoMessage() {}

func (x *StoreValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreValue.ProtoReflect.Descriptor instead.
func (*StoreValue) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *StoreValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *StoreValueResponse) Reset() {
	*x = StoreValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreValueResponse) ProtoMessage() {}

func (x *StoreValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreValueResponse.ProtoReflect.Descriptor instead.
func (*StoreValueResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{3}
}

func (x *StoreValueResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LoadValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LoadValue) Reset() {
	*x = LoadValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadValue) ProtoMessage() {}

func (x *LoadValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadValue.ProtoReflect.Descriptor instead.
func (*LoadValue) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *LoadValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoadValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadValueResponse) Reset() {
	*x = LoadValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadValueResponse) ProtoMessage() {}

func (x *LoadValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadValueResponse.ProtoReflect.Descriptor instead.
func (*LoadValueResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *LoadValueResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoadValueResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_cmd_proto protoreflect.FileDescriptor

var file_v1_cmd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x31, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x0d, 0x76, 0x31, 0x2f, 0x72, 0x61,
	0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x03, 0x0a, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x71, 0x75, 0x61, 0x73,
	0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x35,
	0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12,
	0x42, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x6f, 0x74, 0x65, 0x12, 0x4e, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6e,
	0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x77, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x4e, 0x6f, 0x77, 0x42, 0x05, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x22, 0xd3, 0x03, 0x0a, 0x0f,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x49, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0c, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x6f, 0x74, 0x65,
	0x12, 0x4f, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x73, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x71, 0x75, 0x61,
	0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x12, 0x40, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x6e, 0x6f, 0x77,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x77, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x4e, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x65, 0x73,
	0x70, 0x22, 0x32, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x26, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1d, 0x0a,
	0x09, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x39, 0x0a, 0x11,
	0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x68, 0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2f,
	0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_v1_cmd_proto_rawDescOnce sync.Once
	file_v1_cmd_proto_rawDescData = file_v1_cmd_proto_rawDesc
)

func file_v1_cmd_proto_rawDescGZIP() []byte {
	file_v1_cmd_proto_rawDescOnce.Do(func() {
		file_v1_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_cmd_proto_rawDescData)
	})
	return file_v1_cmd_proto_rawDescData
}

var file_v1_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_cmd_proto_goTypes = []interface{}{
	(*Command)(nil),                 // 0: quasar.v1.Command
	(*CommandResponse)(nil),         // 1: quasar.v1.CommandResponse
	(*StoreValue)(nil),              // 2: quasar.v1.StoreValue
	(*StoreValueResponse)(nil),      // 3: quasar.v1.StoreValueResponse
	(*LoadValue)(nil),               // 4: quasar.v1.LoadValue
	(*LoadValueResponse)(nil),       // 5: quasar.v1.LoadValueResponse
	(*AppendEntriesRequest)(nil),    // 6: quasar.v1.AppendEntriesRequest
	(*RequestVoteRequest)(nil),      // 7: quasar.v1.RequestVoteRequest
	(*InstallSnapshotRequest)(nil),  // 8: quasar.v1.InstallSnapshotRequest
	(*TimeoutNowRequest)(nil),       // 9: quasar.v1.TimeoutNowRequest
	(*AppendEntriesResponse)(nil),   // 10: quasar.v1.AppendEntriesResponse
	(*RequestVoteResponse)(nil),     // 11: quasar.v1.RequestVoteResponse
	(*InstallSnapshotResponse)(nil), // 12: quasar.v1.InstallSnapshotResponse
	(*TimeoutNowResponse)(nil),      // 13: quasar.v1.TimeoutNowResponse
}
var file_v1_cmd_proto_depIdxs = []int32{
	2,  // 0: quasar.v1.Command.store_value:type_name -> quasar.v1.StoreValue
	4,  // 1: quasar.v1.Command.load_value:type_name -> quasar.v1.LoadValue
	6,  // 2: quasar.v1.Command.append_entries:type_name -> quasar.v1.AppendEntriesRequest
	7,  // 3: quasar.v1.Command.request_vote:type_name -> quasar.v1.RequestVoteRequest
	8,  // 4: quasar.v1.Command.install_snapshot:type_name -> quasar.v1.InstallSnapshotRequest
	9,  // 5: quasar.v1.Command.timeout_now:type_name -> quasar.v1.TimeoutNowRequest
	3,  // 6: quasar.v1.CommandResponse.store_value:type_name -> quasar.v1.StoreValueResponse
	5,  // 7: quasar.v1.CommandResponse.load_value:type_name -> quasar.v1.LoadValueResponse
	10, // 8: quasar.v1.CommandResponse.append_entries:type_name -> quasar.v1.AppendEntriesResponse
	11, // 9: quasar.v1.CommandResponse.request_vote:type_name -> quasar.v1.RequestVoteResponse
	12, // 10: quasar.v1.CommandResponse.install_snapshot:type_name -> quasar.v1.InstallSnapshotResponse
	13, // 11: quasar.v1.CommandResponse.timeout_now:type_name -> quasar.v1.TimeoutNowResponse
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_cmd_proto_init() }
func file_v1_cmd_proto_init() {
	if File_v1_cmd_proto != nil {
		return
	}
	file_v1_raft_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_cmd_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Command_StoreValue)(nil),
		(*Command_LoadValue)(nil),
		(*Command_AppendEntries)(nil),
		(*Command_RequestVote)(nil),
		(*Command_InstallSnapshot)(nil),
		(*Command_TimeoutNow)(nil),
	}
	file_v1_cmd_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandResponse_StoreValue)(nil),
		(*CommandResponse_LoadValue)(nil),
		(*CommandResponse_AppendEntries)(nil),
		(*CommandResponse_RequestVote)(nil),
		(*CommandResponse_InstallSnapshot)(nil),
		(*CommandResponse_TimeoutNow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_cmd_proto_goTypes,
		DependencyIndexes: file_v1_cmd_proto_depIdxs,
		MessageInfos:      file_v1_cmd_proto_msgTypes,
	}.Build()
	File_v1_cmd_proto = out.File
	file_v1_cmd_proto_rawDesc = nil
	file_v1_cmd_proto_goTypes = nil
	file_v1_cmd_proto_depIdxs = nil
}
