// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: v1/discovery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerSuffrage int32

const (
	ServerSuffrage_VOTER    ServerSuffrage = 0
	ServerSuffrage_NONVOTER ServerSuffrage = 1
	// Deprecated
	ServerSuffrage_STAGING ServerSuffrage = 2
)

// Enum value maps for ServerSuffrage.
var (
	ServerSuffrage_name = map[int32]string{
		0: "VOTER",
		1: "NONVOTER",
		2: "STAGING",
	}
	ServerSuffrage_value = map[string]int32{
		"VOTER":    0,
		"NONVOTER": 1,
		"STAGING":  2,
	}
)

func (x ServerSuffrage) Enum() *ServerSuffrage {
	p := new(ServerSuffrage)
	*p = x
	return p
}

func (x ServerSuffrage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerSuffrage) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_discovery_proto_enumTypes[0].Descriptor()
}

func (ServerSuffrage) Type() protoreflect.EnumType {
	return &file_v1_discovery_proto_enumTypes[0]
}

func (x ServerSuffrage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerSuffrage.Descriptor instead.
func (ServerSuffrage) EnumDescriptor() ([]byte, []int) {
	return file_v1_discovery_proto_rawDescGZIP(), []int{0}
}

type DiscoverPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender     *ServerInfo `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	IsResponse bool        `protobuf:"varint,2,opt,name=is_response,json=isResponse,proto3" json:"is_response,omitempty"`
}

func (x *DiscoverPing) Reset() {
	*x = DiscoverPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_discovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoverPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPing) ProtoMessage() {}

func (x *DiscoverPing) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPing.ProtoReflect.Descriptor instead.
func (*DiscoverPing) Descriptor() ([]byte, []int) {
	return file_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverPing) GetSender() *ServerInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *DiscoverPing) GetIsResponse() bool {
	if x != nil {
		return x.IsResponse
	}
	return false
}

type ServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId      string         `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerAddress string         `protobuf:"bytes,2,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Suffrage      ServerSuffrage `protobuf:"varint,3,opt,name=suffrage,proto3,enum=quasar.v1.ServerSuffrage" json:"suffrage,omitempty"`
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_discovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_discovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ServerInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerInfo) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerInfo) GetSuffrage() ServerSuffrage {
	if x != nil {
		return x.Suffrage
	}
	return ServerSuffrage_VOTER
}

var File_v1_discovery_proto protoreflect.FileDescriptor

var file_v1_discovery_proto_rawDesc = []byte{
	0x0a, 0x12, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x22,
	0x5e, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x2d, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x87, 0x01, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x75, 0x66, 0x66, 0x72, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x75, 0x66, 0x66, 0x72, 0x61, 0x67, 0x65, 0x52,
	0x08, 0x73, 0x75, 0x66, 0x66, 0x72, 0x61, 0x67, 0x65, 0x2a, 0x36, 0x0a, 0x0e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x75, 0x66, 0x66, 0x72, 0x61, 0x67, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x56,
	0x4f, 0x54, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x4e, 0x56, 0x4f, 0x54,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x65, 0x68, 0x73, 0x70, 0x68, 0x69, 0x6e, 0x78, 0x2f, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_discovery_proto_rawDescOnce sync.Once
	file_v1_discovery_proto_rawDescData = file_v1_discovery_proto_rawDesc
)

func file_v1_discovery_proto_rawDescGZIP() []byte {
	file_v1_discovery_proto_rawDescOnce.Do(func() {
		file_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_discovery_proto_rawDescData)
	})
	return file_v1_discovery_proto_rawDescData
}

var file_v1_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_discovery_proto_goTypes = []interface{}{
	(ServerSuffrage)(0),  // 0: quasar.v1.ServerSuffrage
	(*DiscoverPing)(nil), // 1: quasar.v1.DiscoverPing
	(*ServerInfo)(nil),   // 2: quasar.v1.ServerInfo
}
var file_v1_discovery_proto_depIdxs = []int32{
	2, // 0: quasar.v1.DiscoverPing.sender:type_name -> quasar.v1.ServerInfo
	0, // 1: quasar.v1.ServerInfo.suffrage:type_name -> quasar.v1.ServerSuffrage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_discovery_proto_init() }
func file_v1_discovery_proto_init() {
	if File_v1_discovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_discovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoverPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_discovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_discovery_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_discovery_proto_goTypes,
		DependencyIndexes: file_v1_discovery_proto_depIdxs,
		EnumInfos:         file_v1_discovery_proto_enumTypes,
		MessageInfos:      file_v1_discovery_proto_msgTypes,
	}.Build()
	File_v1_discovery_proto = out.File
	file_v1_discovery_proto_rawDesc = nil
	file_v1_discovery_proto_goTypes = nil
	file_v1_discovery_proto_depIdxs = nil
}
