// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: v1/cmd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Cmd:
	//
	//	*Command_StoreValue
	//	*Command_LoadValue
	Cmd isCommand_Cmd `protobuf_oneof:"cmd"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{0}
}

func (m *Command) GetCmd() isCommand_Cmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (x *Command) GetStoreValue() *StoreValue {
	if x, ok := x.GetCmd().(*Command_StoreValue); ok {
		return x.StoreValue
	}
	return nil
}

func (x *Command) GetLoadValue() *LoadValue {
	if x, ok := x.GetCmd().(*Command_LoadValue); ok {
		return x.LoadValue
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_StoreValue struct {
	StoreValue *StoreValue `protobuf:"bytes,1,opt,name=store_value,json=storeValue,proto3,oneof"`
}

type Command_LoadValue struct {
	LoadValue *LoadValue `protobuf:"bytes,2,opt,name=load_value,json=loadValue,proto3,oneof"`
}

func (*Command_StoreValue) isCommand_Cmd() {}

func (*Command_LoadValue) isCommand_Cmd() {}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Resp:
	//
	//	*CommandResponse_StoreValue
	//	*CommandResponse_LoadValue
	Resp isCommandResponse_Resp `protobuf_oneof:"resp"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{1}
}

func (m *CommandResponse) GetResp() isCommandResponse_Resp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func (x *CommandResponse) GetStoreValue() *StoreValueResponse {
	if x, ok := x.GetResp().(*CommandResponse_StoreValue); ok {
		return x.StoreValue
	}
	return nil
}

func (x *CommandResponse) GetLoadValue() *LoadValueResponse {
	if x, ok := x.GetResp().(*CommandResponse_LoadValue); ok {
		return x.LoadValue
	}
	return nil
}

type isCommandResponse_Resp interface {
	isCommandResponse_Resp()
}

type CommandResponse_StoreValue struct {
	StoreValue *StoreValueResponse `protobuf:"bytes,1,opt,name=store_value,json=storeValue,proto3,oneof"`
}

type CommandResponse_LoadValue struct {
	LoadValue *LoadValueResponse `protobuf:"bytes,2,opt,name=load_value,json=loadValue,proto3,oneof"`
}

func (*CommandResponse_StoreValue) isCommandResponse_Resp() {}

func (*CommandResponse_LoadValue) isCommandResponse_Resp() {}

type StoreValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StoreValue) Reset() {
	*x = StoreValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreValue) ProtoMessage() {}

func (x *StoreValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreValue.ProtoReflect.Descriptor instead.
func (*StoreValue) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{2}
}

func (x *StoreValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreValue) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type StoreValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreValueResponse) Reset() {
	*x = StoreValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreValueResponse) ProtoMessage() {}

func (x *StoreValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreValueResponse.ProtoReflect.Descriptor instead.
func (*StoreValueResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{3}
}

type LoadValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *LoadValue) Reset() {
	*x = LoadValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadValue) ProtoMessage() {}

func (x *LoadValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadValue.ProtoReflect.Descriptor instead.
func (*LoadValue) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{4}
}

func (x *LoadValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LoadValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadValueResponse) Reset() {
	*x = LoadValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_cmd_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadValueResponse) ProtoMessage() {}

func (x *LoadValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cmd_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadValueResponse.ProtoReflect.Descriptor instead.
func (*LoadValueResponse) Descriptor() ([]byte, []int) {
	return file_v1_cmd_proto_rawDescGZIP(), []int{5}
}

func (x *LoadValueResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_cmd_proto protoreflect.FileDescriptor

var file_v1_cmd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x31, 0x2f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x71, 0x75, 0x61,
	0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x35, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x61,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x22, 0x9a, 0x01,
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x22, 0x32, 0x0a, 0x0a, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x14,
	0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x0a, 0x09, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x20, 0x5a, 0x1e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x68, 0x73, 0x70,
	0x68, 0x69, 0x6e, 0x78, 0x2f, 0x71, 0x75, 0x61, 0x73, 0x61, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_cmd_proto_rawDescOnce sync.Once
	file_v1_cmd_proto_rawDescData = file_v1_cmd_proto_rawDesc
)

func file_v1_cmd_proto_rawDescGZIP() []byte {
	file_v1_cmd_proto_rawDescOnce.Do(func() {
		file_v1_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_cmd_proto_rawDescData)
	})
	return file_v1_cmd_proto_rawDescData
}

var file_v1_cmd_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_cmd_proto_goTypes = []interface{}{
	(*Command)(nil),            // 0: quasar.v1.Command
	(*CommandResponse)(nil),    // 1: quasar.v1.CommandResponse
	(*StoreValue)(nil),         // 2: quasar.v1.StoreValue
	(*StoreValueResponse)(nil), // 3: quasar.v1.StoreValueResponse
	(*LoadValue)(nil),          // 4: quasar.v1.LoadValue
	(*LoadValueResponse)(nil),  // 5: quasar.v1.LoadValueResponse
}
var file_v1_cmd_proto_depIdxs = []int32{
	2, // 0: quasar.v1.Command.store_value:type_name -> quasar.v1.StoreValue
	4, // 1: quasar.v1.Command.load_value:type_name -> quasar.v1.LoadValue
	3, // 2: quasar.v1.CommandResponse.store_value:type_name -> quasar.v1.StoreValueResponse
	5, // 3: quasar.v1.CommandResponse.load_value:type_name -> quasar.v1.LoadValueResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_cmd_proto_init() }
func file_v1_cmd_proto_init() {
	if File_v1_cmd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_cmd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_cmd_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_cmd_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Command_StoreValue)(nil),
		(*Command_LoadValue)(nil),
	}
	file_v1_cmd_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CommandResponse_StoreValue)(nil),
		(*CommandResponse_LoadValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_cmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_cmd_proto_goTypes,
		DependencyIndexes: file_v1_cmd_proto_depIdxs,
		MessageInfos:      file_v1_cmd_proto_msgTypes,
	}.Build()
	File_v1_cmd_proto = out.File
	file_v1_cmd_proto_rawDesc = nil
	file_v1_cmd_proto_goTypes = nil
	file_v1_cmd_proto_depIdxs = nil
}
